services:
  # --- SERVICIO 1: LA BASE DE DATOS ---
  myshop-db:
    image: mysql:8.0
    container_name: myshop-db-container
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      # Blindaje de puerto: Solo accesible desde el propio servidor, bloqueando bots externos
      - "127.0.0.1:3306:3306"
    volumes:
      - myshop_db_data:/var/lib/mysql

  # --- SERVICIO 2: TU APLICACIÓN JAVA ---
  myshop-app:
    build: .
    container_name: myshop-app-container
    restart: always
    depends_on:
      - myshop-db
    ports:
      # Blindaje de puerto: Nginx será el encargado de exponerlo al mundo de forma segura
      - "127.0.0.1:8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://myshop-db:3306/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
      
      # Variables para Cloudinary
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      
      # Variable de seguridad
      - JWT_SECRET=${JWT_SECRET}

volumes:
  myshop_db_data: